# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-02 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_stock_names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('symbol', models.CharField(max_length=5)),
                ('sector', models.CharField(max_length=30, null=True)),
                ('industry', models.CharField(max_length=50, null=True)),
                ('marketCap', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='bloombergStockSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('headline', models.CharField(max_length=255)),
                ('postDate', models.DateTimeField()),
                ('dateCrawled', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField()),
                ('articleHTML', models.TextField(default='html should be here')),
                ('stockTicker', models.TextField(default='XXXX', max_length=5)),
                ('sentiment', models.TextField(default='unknown', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='cnbcStockSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('headline', models.CharField(max_length=255)),
                ('postDate', models.DateTimeField()),
                ('dateCrawled', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField()),
                ('articleHTML', models.TextField(default='html should be here')),
                ('stockTicker', models.TextField(default='XXXX', max_length=5)),
                ('sentiment', models.TextField(default='unknown', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='stockSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('headline', models.CharField(max_length=255)),
                ('postDate', models.DateTimeField()),
                ('dateCrawled', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField()),
                ('articleHTML', models.TextField(default='html should be here')),
                ('stockTicker', models.TextField(default='XXXX', max_length=5)),
            ],
        ),
    ]
